# Generated by Django 5.2.1 on 2025-05-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
