# Generated by Django 5.2.1 on 2025-06-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_feedback_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='feedback_pics/'),
        ),
    ]
